### ISSUE TITLE
RS09 - Zombies por enemigo según nivel.

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#10]
- Descripción: Por cada enemigo se debe agregar una cantidad X de zombies cerca de él, con la cantidad X dependiendo de la dificultad en la que se está jugando.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: Cumple.  
- Incremento: 1  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU10 - Número de zombies](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru10---n%C3%BAmero-de-zombies)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by elbraulio** [comment]
**Initialization**
Al iniciar el juego,  hacer spawn de zombies cerca de cada monstruo

**Comment by elbraulio** [comment]
**Concept Location**
El Spawn de objetos se hace solo en Actions.java

**Comment by elbraulio** [comment]
**Impact Analysis**

Análisis con JRipples.
Clases que se podrían ver impactadas:
- Actions
- ActionsFunctions
- mobj_t
- AbstractLevelLoader
- UnifiedGameMap
- player_t
- SlideDoor
- VanillaDSG
- DoomMain
- DoomContext

**Comment by elbraulio** [comment]
**Prefactorig**
Se agregará al metodo SpawnMapThing(), que al hacer Spawn de un objeto y este objeto se mueve (tiene velocidad > 0) se asume que es un monstru y se hace spawn de un zombie dependiendo de la dificultad.

**Comment by juakotorres** [comment]
Se modificó la condición por isMonster(), que verifica si el objeto seleccionado es un monstruo.  
Además se crearon dos nuevos métodos en Actions:  createNewZombiesSurroundings, checkMobjInBounds.  
El método createNewZombiesSurroundings toma como parámetros el número de spawns que se quieren hacer, el radio de inserción máximo, la posición en z y el objeto mapthing (objeto dentro del mapa). Este método toma como centro la posición del objeto, creo un nuevo zombie y posteriormente verifica si este esta dentro del mapa y no esta en la misma posición que otro objeto con el método checkMobjInBounds, crea tantos zombies como el número de spawns entregado.  
El método checkMobjInBounds chequea que el objeto entregado este dentro del mapa o no esta en la misma posición que otro objeto, si esto esta bien inicializa correctamente el objeto creado, sino lo elimina del mapa.

**Comment by juakotorres** [comment]
**Change Propagation**

La única clase impacta fue Actions.

**Comment by juakotorres** [comment]
**Verification**

Funciona correctamente por lo que no se necesita **postfactoring**.

**Comment by juakotorres** [comment]
**Conclusion**

Según la dificultad se producen zombies alrededor de los monstruos.
