### ISSUE TITLE
RS12 - Correr por tiempo limitado

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#13]
- Descripción: El jugador debe tener la posibilidad de moverse a una velocidad mayor a la por defecto por un tiempo limitado.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU12 - Aguante del Jugador](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru12---aguante-del-jugador)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by SetaSouto** [comment]
Initialization: Se debe buscar como está implementado el jugador y su movimiento.
Concept location: Player, Move, Run.

Nota importante: Se encontró el mecanismo de acuerdo el jugador avanza y la velocidad correspondiente. Se encuentra en el archivo jugador_t.java y la constante que maneja la velocidad es PLAYERTHRUST. A priori maneja números múltiplos de 2.

**Comment by SetaSouto** [comment]
##### Impact Análisis:

Análisis con JRipples.
Clases que se podrían ver impactadas:
- RendererState
- ActionFunctions
- player_t
- StatusBar
- Actions
- UnifiedGameMap
- ViewVars
- Map
- EndLevel
- mobj_t
- DoomStatus
- DoomMain
- VanillaDSG
- ParallelRenderer
- HU

**Comment by SetaSouto** [comment]
#### Prefactoring:

El juego ya incluye la posiblidad de moverse a una velocidad más rápida que la normal, se debe presionar la tecla _shift_. La solución consiste en implementar una variable que indica que tan cansado está el jugador. Se cansa mientras corre, por ende al alcanzar el máximo para de correr.

**Comment by SetaSouto** [comment]
#### Change propagation:

La única clase impactada es _player_t_.

**Comment by SetaSouto** [comment]
#### Verification

Lo implementado funciona correctamente. No es necesario **postfactoring**.

**Comment by SetaSouto** [comment]
#### Conclusion

El jugador ahora corre por un tiempo limitado, el cual depende de qué _tan cansado_ está el jugador de acuerdo a una variable _tired_ que aumenta mientras corre.
