### ISSUE TITLE
RS13 - Correr varía según dificultad

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#14]
- Descripción: Implementar límite de tiempo para correr que varía según dificultad.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU12 - Aguante del Jugador](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru12---aguante-del-jugador)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by SetaSouto** [comment]
#### Initialization

Se debe buscar como están implementados los diferentes tipos de dificultad.

**Comment by SetaSouto** [comment]
#### Concept Location

Difficulty, skill, player.

**Comment by SetaSouto** [comment]
#### Impact Analysis

Análisis con JRipples.
Clases que se podrían ver impactadas:
- RendererState
- AbstractStatusBar
- Map
- Wiper
- DoomSystem
- ParallelRender
- DummyNetworkDriver
- EndLevel
- DoomFrame
- UnifiedGameMap
- DoomMain
- TestClipSound
- TestClassicSound
- Main
- DoomContext
- TestSuperSound
- AWTDoom
- LevelLoaderTester
- MochaEvents
- HU
- ActionFunctions
- player_t
- StatusBar
- Actions
- ViewVars
- Map
- EndLevel
- mobj_t
- DoomStatus
- VanillaDSG

**Comment by SetaSouto** [comment]
#### Prefactoring

Al iniciarse un juego nuevo (o cargado) se actualiza el nivel de dificultad para todos los jugadores. Con esto se setea la variable _maxTired_. En el nivel más difícil _maxTired_ es más pequeño y en el nivel más fácil _maxTired_ es grande. Esto quiere decir que tiene más tiempo para cansarse en el nivel fácil por ejemplo.

**Comment by SetaSouto** [comment]
#### Change Propagation

Se vieron afectadas las clases _DoomMain_ y la clase _player_t_.

**Comment by SetaSouto** [comment]
#### Verification

Lo implementado funciona, se agregó el _DoomMain_ una sección que al iniciar cada vez un juego nuevo actualiza el _skill_ en los jugadores (_player_t_) y de esta manera se actualiza el _maxTired_.

No es necesario **postfactoring**.

**Comment by SetaSouto** [comment]
#### Conclusion

Ahora el jugador se va a cansar más rápido o más lento dependiendo del nivel de dificultad en la cual se encuentra.
