### ISSUE TITLE
RS14 - Cansancio Jugador

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#15]
- Descripción: Implementar el estado de cansancio del jugador durante el cual camina lentamente.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU12 - Aguante del Jugador](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru12---aguante-del-jugador)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by SetaSouto** [comment]
#### Initialization

Debemos implementar la manera de que cuando el jugador se encuentre cansado en realidad no pueda correr, solo caminar.

**Comment by SetaSouto** [comment]
#### Concept Location

Move, run, player.

**Comment by SetaSouto** [comment]
#### Impact Análisis:

Análisis con JRipples.
Clases que se podrían ver impactadas:
- RendererState
- ActionFunctions
- player_t
- StatusBar
- Actions
- UnifiedGameMap
- ViewVars
- Map
- EndLevel
- mobj_t
- DoomStatus
- DoomMain
- VanillaDSG
- ParallelRenderer
- HU

**Comment by SetaSouto** [comment]
#### Prefactoring

Se seteara un tiempo de espera en el cual el jugador debe estar en el _maxTired_. Es decir cuando el jugador se canse deberá esperar un tiempo para poder comenzar a descansar, lo que llevará a que el jugador no pueda correr durante este tiempo.

**Comment by SetaSouto** [comment]
#### Change propagation

La única clase impactada es _player_t_.

**Comment by SetaSouto** [comment]
#### Verification

Se modificó de tal manera de que el jugador va a poder descansar solamente si no está corriendo, que no esté en el tope de cansancio y esperado el tiempo correspondiente. Al pasar el tiempo _waitTired_ el jugador puede volver a descansar y de esta manera volver a correr.

**Nota:** El jugador puede volver a correr luego del tiempo pero notar que su cansancio no vuelve a cero inmediatamente, comienza recién a descansar, es decir para volver a correr con todo su cansancio esperado debe seguir descansando. Esto lleva a escenarios donde, por ejemplo, se canse muy rápido nuevamente, es decir, el jugador puede cansarse e intentar seguir corriendo y al momento de que se cumpla el tiempo de espera correrá de nuevo, pero se cansará inmediatamente porque no alcanzó a descansar suficiente.  
Se escogió esta manera pues resulta mucho más real al momento de jugar.

No es necesario **postfactoring**.

**Comment by SetaSouto** [comment]
#### Conclusion

El jugador ahora cuando se cansa se le ve imposible poder correr hasta que pase un tiempo de espera. De esta manera se ve obligado a caminar no más.
