### ISSUE TITLE
RS15 - Cansancio según dificultad

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#16]
- Descripción: Implementar el tiempo de cansancio dependiente de la dificultad.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU12 - Aguante del Jugador](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru12---aguante-del-jugador)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by SetaSouto** [comment]
#### Initialization

Se debe implementar que el tiempo en el cual debe permanecer en el estado de cansancio máximo dependa de la dificultad. Así tenga que estar más rato caminando si está en un nivel más difícil.

**Comment by SetaSouto** [comment]
#### Concept Location

Move, run, skill.

**Comment by SetaSouto** [comment]
#### Impact Analysis

Análisis con JRipples.
Clases que se podrían ver impactadas:
- RendererState
- AbstractStatusBar
- Map
- Wiper
- DoomSystem
- ParallelRender
- DummyNetworkDriver
- EndLevel
- DoomFrame
- UnifiedGameMap
- DoomMain
- TestClipSound
- TestClassicSound
- Main
- DoomContext
- TestSuperSound
- AWTDoom
- LevelLoaderTester
- MochaEvents
- HU
- ActionFunctions
- player_t
- StatusBar
- Actions
- ViewVars
- Map
- EndLevel
- mobj_t
- DoomStatus
- VanillaDSG

**Comment by SetaSouto** [comment]
#### Prefactoring

Utilizando lo que ocupamos para la [RS13](https://github.com/njara/mochadoom/issues/14) el jugador ya sabe en que nivel de ficiultad está. O sea simplemente debemos implementar que la variable _waitTired_ depende de ese nivel.

**Comment by SetaSouto** [comment]
#### Change propagation

La única clase impactada es _player_t_.

**Comment by SetaSouto** [comment]
#### Verification

Se implementó el método que setea el _waitTired_ de acuerdo al nivel de dificultad. Funciona correctamente, no es necesario **postfactoring**.

**Comment by SetaSouto** [comment]
#### Conclusion

El jugador ahora debe esperar más tiempo en el estado cansado si está en un nivel más difícil.
