### ISSUE TITLE
RS20 - Cheatcodes

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#17]
- Descripción: Actualmente ya existen cheatcodes en el juego, por lo que la primera tarea es identificar como están implementados para desarrollar los propios.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU13- Cheatcodes](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru13---cheatcodes)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Lapnis** [comment]
### Initialization

Se debe encontrar la forma en que estan implementados y el funcionamiento de los cheatcodes en el juego.

**Comment by Lapnis** [comment]
### Concept Location

cheat, cheatcode

**Comment by Lapnis** [comment]
### Impact Analysis

Analizando con JRipples, las clases que podrían verse impactadas son las siguientes:
- cheatseq_t

**Comment by Lapnis** [comment]
### Prefactoring

Se debe buscar de que forma se encuentran implementados los cheatcodes existentes en el juego, los cuales son definidos con la clase cheatseq_t.

**Comment by Lapnis** [comment]
### Change Propagation

Los cheatcodes se manejan creando un objeto de la clase cheatseq_t. A este objeto se le pasa un arreglo de caracteres (que corresponden a la palabra a teclear para activar el cheatcode), y el indice donde comienza el arreglo (que siempre será 0). Luego, cada vez que hay eventos en el teclado, se debe verificar si la secuencia ingresada por el usuario corresponde a algun cheat existente. Para ello, se le aplica a los objetos cheatseq_t el metodo CheckCheat(char). Si lo que ingreso el usuario resulta ser una secuencia valida, se procede a activar el cheat.

**Comment by Lapnis** [comment]
### Verification

Se logró obtener toda la información necesaria para implementar nuevos cheatcodes.

**Comment by Lapnis** [comment]
### Conclusion

Para definir nuevos cheatcodes, basta con crear objetos de la clase cheatseq_t, y hacer CheckCheat en las partes donde se manejen los eventos del teclado.
