### ISSUE TITLE
RS21 - Cambiar tamaño del mapa actual

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#18]
- Descripción: Se debe cambiar el tamaño a uno más pequeño. El tamaño debe ser chico para para poder ser visibe en la pantalla sin entorpecer la vision del juego.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU14 - Cheatcode: Activar mapa](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru14---cheatcode-activar-mapa)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Lapnis** [comment]
### Initialization

Se debe ser capaz de cambiar el tamaño del mapa actual por uno de menor tamaño.

**Comment by Lapnis** [comment]
### Concept Location

Los conceptos clave para resolver esta issue son: map, size.

**Comment by Lapnis** [comment]
### Impact Analysis

Analisis con JRipples muestra que las posibles clases impactadas serían: 
- Map
- DoomMain

**Comment by Lapnis** [comment]
### Prefactoring

El mapa se dibuja en la clase Map. Aqui existen metodos que dibujan todas las lineas que definen el mapa. Habría que ver como funcionan estos metodos, y tratar de a aplicar una traslación y redimesion a las lineas que se dibujan para moverlas y hacerlas mas cortas.

**Comment by Lapnis** [comment]
### Change Propagation

Se trata de modificar el método que dibuja las lineas del mapa (las paredes), pero se encontró con diversos errores como por ejemplo, que las lineas se dibujan pixel a pixel, y estas estan definidas en el archivo wad que tiene toda la informacion de los niveles del juego. Por ende, a priori no hay una forma de saber su largo para poder aplicarle una redimension a la linea. Ademas tambien se trato de mover el mapa, pero las lineas que salian por un extermo de la pantalla aparecian por el otro extremo, causando un glitch grafico en la statusbar y generando algunas excepciones que botaban el juego.

**Comment by Lapnis** [comment]
### Verification

Dadas las dificultades encontradas, se nos sugirió no hacer el redimensionamiento del mapa, pero si poder verlo al mismo tiempo que se juega, es decir, que no tenga un fondo negro, si no un fondo transparente.

**Comment by Lapnis** [comment]
### Conclusion

La implementación de un mapa con fondo transparente se vera en la [RS22](https://github.com/njara/mochadoom/issues/19)
