### ISSUE TITLE
RS23 - Cheatcode "marcopolo"

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#20]
- Descripción: Al ingresar el cheatcode "marcopolo", se debe mostrar el mapa en la esquina superior derecha de la pantalla.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU14 - Cheatcode: Activar mapa](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru14---cheatcode-activar-mapa)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Lapnis** [comment]
### Initialization

Implementar cheatcode para activar la transparencia del mapa implementada en [RS22](https://github.com/njara/mochadoom/issues/19).

**Comment by Lapnis** [comment]
### Concept Location

Los conceptos mas relevantes de esta implementacion son: map, background, cheat, cheatcode.

**Comment by Lapnis** [comment]
### Impact Analysis

Las clases que podrían verse afectadas son las siguientes:
- Map
- DoomMain

**Comment by Lapnis** [comment]
### Prefactoring

Como ya se sabe como implementar nuevos cheatcodes, basta buscar donde se manejan eventos del teclado, crear un objeto cheatseq_t que contendra la secuencia que activará el cheatcode, y luego activar lo que se resolvio en [RS22](https://github.com/njara/mochadoom/issues/19)

**Comment by Lapnis** [comment]
### Change Propagation

La implementación funciona sin mayores problemas. Para activar la transparencia del mapa, solo basta escribir "marcopolo" en la vista del jugador (o sea, no con el mapa activado), y la proxima vez que se active el mapa este aparecerá con un fondo transparente

**Comment by Lapnis** [comment]
### Verification

Dado que no hay mayores problemas, no se necesita de postfactoring

**Comment by Lapnis** [comment]
### Conclusion

Escribiendo "marcopolo" sin tener el mapa abierto, activa la transparencia del mapa, permitiendo jugar con el mapa abierto siempre.
