### ISSUE TITLE
RS24 - Zombies en el mapa

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#21]
- Descripción: Mostrar la ubicación de los zombies en el mapa.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU15 - Cheatcode ver zombies y su tipo en el mapa](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru15---cheatcode-ver-zombies-y-su-tipo-en-el-mapa)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by SetaSouto** [comment]
### Initialization

Se debe identificar a todos los zombies del juego y ser capaz de mostrarlos en el mapa.

**Comment by SetaSouto** [comment]
### Concept Location

Zombie, map.

**Comment by SetaSouto** [comment]
### Impact Analysis

Análisis con JRipples.
Clases que se pueden ver impactadas:
- DoomMain
- Map
- info
- GrayZombie_t
- mobj_t
- sounds
- mobjinfo_t
- RedZombie_t
- BlackZombie_t
- fixed_t
- state_t
- GreenZombie_t
- MT_Player_t

**Comment by SetaSouto** [comment]
### Prefactoring

Cuando se dibujen todos los objetos en el mapa (con el truco iddt) se mostrarán los zombies de acuerdo a su propio color. Dado que el fondo del mapa es negro, el zombie black se dibuja amarillo.

**Comment by SetaSouto** [comment]
### Change propagation

La única clase impactada es _Map.java_.

**Comment by SetaSouto** [comment]
### Verification

La solución funciona como lo esperado, se agregó un método de dibuja el zombie de acuerdo a qué tipo es. No necesita **postfactoring**.

**Comment by SetaSouto** [comment]
### Conclusion

Los zombies ahora son mostrados en el mapa cuando se dibujan todos los objetos. Se puede identificar el tipo del zombie a través del mapa.
