### ISSUE TITLE
RS25 - Tipos de zombie en el mapa

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#22]
- Descripción: En el mapa se debe poder diferenciar entre los tipos de zombies por el color.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU15 - Cheatcode: Ver zombies y su tipo en el mapa](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru15---cheatcode-ver-zombies-y-su-tipo-en-el-mapa)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by SetaSouto** [comment]
### Initialization

Se debe poder diferencias a los zombies por su color en el mapa.

**Comment by SetaSouto** [comment]
### Concept Location

Zombie, Map.

**Comment by SetaSouto** [comment]
### Impact Analysis

Análisis con JRipples.
Clases que se podrían ver impactadas:
- Map
- DoomMain

**Comment by SetaSouto** [comment]
### Prefactoring

Se debe agregar un método que permita diferencias por tipo de zombie y cada uno dibujarlo con un color distinto.

**Comment by SetaSouto** [comment]
### Change propagation

La única clase impactada es _Map.java_.

**Comment by SetaSouto** [comment]
### Verification

Se desarrolló en conjunto con la issue [RS24](https://github.com/njara/mochadoom/issues/21) y resultó bien. No necesita **postfactoring**.

**Comment by SetaSouto** [comment]
### Conclusion

Los zombies se logran ver y diferenciar su tipo en el mapa.
