### ISSUE TITLE
RS26 - Cheatcode "iseeyou"

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#23]
- Descripción: Al ingrear el cheatcode  "iseeyou" se debe mostrar los zombies y su tipo en el mapa.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU15 - Cheatcode: Ver zombies y su tipo en el mapa](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru15---cheatcode-ver-zombies-y-su-tipo-en-el-mapa)

Al ingrear el cheatcode  "iseeyou" se debe mostrar los zombies y su tipo en el mapa.
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by SetaSouto** [comment]
### Initialization

Se debe implementar un cheatcode que permita mostrar sólo los zombies en el mapa.

**Comment by SetaSouto** [comment]
### Concept Location

Map, zombie.

**Comment by SetaSouto** [comment]
### Impact analysis

Análisis con JRipples.
Clases que se podrían ver impactadas:
- Map
- DoomMain

**Comment by SetaSouto** [comment]
### Prefactoring

Se debe generar un truco que permita visualizar a los zombies sin necesidad del truco iddt.

**Comment by SetaSouto** [comment]
### Change propagation

La única clase impactada es _Map.java_.

**Comment by SetaSouto** [comment]
### Verification

Se creó un truco nuevo que se puede ingresar como "shwz" y muestra a los zombies en el mapa. El mapa debe estar abierto para poder utilizar el truco. No necesita **postfactoring**.

**Comment by SetaSouto** [comment]
### Conclusion

Se logró lo esperado, el truco funciona bien y se muestra a loa zombies y sus respectivos colores.
