### ISSUE TITLE
RS16 - Probabilidad Color Zombie

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#25]
- Descripción: El jugador y los monstruos al transformarse en zombie tienen una probabilidad de tener un color, ordenados de mayor a menor probabilidad: Verde, Rojo, Gris, Negro.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/7/2016 12:12  
- Estado: Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU03 - Probabilidad de cada tipo de zombie](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru03---probabilidad-de-cada-tipo-de-zombie)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by elbraulio** [comment]
Se debe crear una funcion de probabilidad (variable aleatoria (? ) que entregue el tipo de zombie que debe aparecer luego de una muerte.

**Comment by elbraulio** [comment]
Se localizó en Actions.java el respawn de unidades, alli sera el spawn de zombies y por lo tanto alli debe ir la funcion de prob.

**Comment by elbraulio** [comment]
Sólo se verá afectada la clase Actions

**Comment by elbraulio** [comment]
**Prefactoring**
Se modificó la clase Actions, donde ocurre el Spawn de zombies, agregando la probabilidad del zombie. Sólo falta incluir la prob. segun el nivel de dificultad. (8f7838a11a133b6680f339c5468d03850fbb4692)

**Comment by elbraulio** [comment]
7f71bf0f420c9cd01f1ede32947e852e0adeda7f Ahora la probabilidad es afectada por la dificultad de juego.

### Lista de probabilidades en %:

**sk_baby** 

```
          greenProb = 100;
          redProb = 0;
          grayProb = 0;
          blackProb = 0;
```

**sk_easy**

```
          greenProb = 70;
          redProb = 20;
          grayProb = 10;
          blackProb = 0;
```

**sk_medium**

```
          greenProb = 50;
          redProb = 30;
          grayProb = 15;
          blackProb = 5;
```

**sk_hard**

```
          greenProb = 20;
          redProb = 30;
          grayProb = 30;
          blackProb = 20;
```

**sk_nightmare**

```
          greenProb = 10;
          redProb = 20;
          grayProb = 30;
          blackProb = 40;
```

**Comment by elbraulio** [comment]
**change propagation**
Sólo se modifico la clase Actions.java

**Comment by elbraulio** [comment]
e68bded0f7cd0939cfe078020d329dc4fe87e688 se actualizaron las prob de tipos de zombies para los modos _hard_ y _nightmare_.
sk_hard
`
          greenProb = 20;
          redProb = 30;
          grayProb = 30;
          blackProb = 20;
`
sk_nightmare
`
          greenProb = 10;
          redProb = 20;
          grayProb = 30;
          blackProb = 40;
`

**Comment by elbraulio** [comment]
**Verification**
Se unió sin problemas a la rama zombie  ba108c9fcc4035313a695c3dc916ade8372d36d8

**Comment by elbraulio** [comment]
**Postfactoring**
No fue necesario modificar nada más, ya que funcionó correctamente.

**Comment by elbraulio** [comment]
**Conclusion**
Los zombies al aparecer tienen distintas probabilidades de ser de alguno de los colores dependiendo de la dificultad de juego. Ademas el zombie verde siempre tiene mayor probabilidad de aparecer.
