### ISSUE TITLE
RS17  - Modo alternativo: BFG 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#26]
- Descripción: Efecto de disparar en todas las direcciones y dañar al jugador
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU24 - Modo alternativo BFG](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru24---modo-alternativo-bfg)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by xZeok** [comment]
Initialization: Se agregara el disparar en todas las direcciones y que dañe al jugador

**Comment by xZeok** [comment]
Concept Location:

/gamelogic/ActionFunctions.java

**Comment by xZeok** [comment]
Impact Analisis:

/gamelogic/ActionFunctions.java
/doom/player_t.java

**Comment by xZeok** [comment]
Prefactoring: Se añadira que el disparo secundario dispare en muchas direcciones diferentes y que dañe al jugador.

**Comment by xZeok** [comment]
(se implemento el disparo en muchas direcciones del disparo secundario de la BFG, falta que dañe al jugador al usarlo)

**Comment by xZeok** [comment]
(se añadio el daño al jugador, se daña 30% al usar el modo alternativo)

**Comment by xZeok** [comment]
Change Propagation:

/gamelogic/ActionFunctions.java
/doom/player_t.java

**Comment by xZeok** [comment]
Verification:

Al usar el modo alternativo de la BFG se realiza disparos en todas las direcciones, se gastan todas las balas, y daña al jugador en un 30%

**Comment by xZeok** [comment]
Postfactoring:

No requiere postfactoring

**Comment by xZeok** [comment]
Conclusion: 

Se añadio el disparo en todas direcciones y daño al jugador
