### ISSUE TITLE
RS18 - Modo alternativo: BFG 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#27]
- Descripción: Tipo de disparo que usa todas las municiones
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU24 - Modo alternativo BFG](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru24---modo-alternativo-bfg)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by xZeok** [comment]
Inicialization: Implementar disparo secundario a BFG y que este gaste todas las munciones

**Comment by xZeok** [comment]
Concept Location:

/gamelogic/ActionFunctions.java

**Comment by xZeok** [comment]
Impact Analisis:

/gamelogic/ActionFunctions.java
/data/info.java
/doom/think_k.java
/doom/items.java
/defines/StateNum.java

**Comment by xZeok** [comment]
Prefactoring: Se implementara el disparo secundario de la BFG y éste gastara todas las balas de BFG

**Comment by xZeok** [comment]
Change Propagation:

/gamelogic/ActionFunctions.java
/data/info.java
/doom/think_k.java
/doom/items.java
/defines/StateNum.java

**Comment by xZeok** [comment]
Verification: Se comprobo la funcionalidad, al disparar el disparo secundario se gastan todas las balas de la BFG.

**Comment by xZeok** [comment]
Postfactoring: no se requiere postfactoring

**Comment by xZeok** [comment]
Conclusion: se implemento el disparo secundario de la BFG y este gasta todas las balas al usarse.
