### ISSUE TITLE
RS19 - Modo alternativo: Plasma gun - daño periodico

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#28]
- Descripción: Implementar a plasma gun secundaria efecto de quemado que daña periódicamente
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 08/04/2016 13:15
- Estado: No Cumple. 
- Incremento: 4
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación. 

Requisito de Usuario asociado
[RU23 - Modo alternativo Plasma gun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru23---modo-alternativo-plasma-gun)
Issues asociados:
[RS28 - Modo alternativo: Plasma gun](https://github.com/njara/mochadoom/issues/28)
[RS45 - Modo alternativo: Plasma gun - esparcir quemado](https://github.com/njara/mochadoom/issues/60)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by pablogomezm** [comment]
Aclaración: daño periódico es en el enemigo, no en el jugador (como lo era con otra arma)

**Comment by pablogomezm** [comment]
**Initialization:** Asociarle al disparo secundario de plasma gun, un efecto de quemado

**Comment by pablogomezm** [comment]
**Concept Location:**
- /data/info.java
- /gamelogic/Actions.java
- /gamelogic/mobj_t.java

**Comment by pablogomezm** [comment]
**Impact Analysis:**
- /data/info.java
- /data/mobjtype_t.java
- /defines/StateNum.java
- /gamelogic/ActionFunctions.java
- /gamelogic/Actions.java
- /gamelogic/mobj_t.java

**Comment by pablogomezm** [comment]
**Prefactoring:**
La estrategia fue ubicar una parte del código que se ejecutara constantemente y ubicar ahi un efecto de quemado/daño periodico

**Comment by pablogomezm** [comment]
**Change propagation:**
La función de quemado se definió en gamelogic/mobj_t.java, y la aplicación en la función Move de gamelogic/Actions.java
Commit asociado: https://github.com/njara/mochadoom/commit/f65b12010c43d7a3c3abedff039a156852ba8f74

**Comment by pablogomezm** [comment]
**Verification:**
Se probaron los cambios ejecutando el juego con el iwad freedom1 (-iwad freedoom1.wad).
Escenario de prueba: mapa military labs, idfka, 6, abrir la puerta, disparar un par de disparos secundarios de plasma a los enemigos, esperar a ver si mueren debido al quemado.

**Comment by pablogomezm** [comment]
**Postfactoring y conclusión:**
Efecto de quemado de disparo secundario de plasma gun funciona correctamente. Objetivos adicionales no obligatorios podrían ser cambiar color del disparo secundario o hacer que el enemigo cambie de color al estar quemado.
