### ISSUE TITLE
RS28 - Modo alternativo: Plasma gun

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#29]
- Descripción: Tipo de disparo con probabilidad de activar efecto de quemado (daño periódico)
- Fuente: Analista.  
- Prioridad: Crítica.
- Estabilidad: Intransable.
- Fecha Actualización: 7/06/2016 12:12
- Estado: Cumple.
- Incremento: 9
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requisito de Usuario asociado
[RU23 - Modo alternativo Plasma gun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru23---modo-alternativo-plasma-gun)
Issues asociados:
[RS19 - Modo alternativo: Plasma gun - daño periodico](https://github.com/njara/mochadoom/issues/28)
[RS45 - Modo alternativo: Plasma gun - esparcir quemado](https://github.com/njara/mochadoom/issues/60)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by pablogomezm** [comment]
**Initialization:** Crear disparo secundario para plama gun, debe tener probabilidad de activar un efecto de quemado

**Comment by pablogomezm** [comment]
**Concept Location:** Módulos principales que deben modificarse para tener un disparo secundario (_ver [wiki respecto a disparos secundarios](https://github.com/njara/mochadoom/wiki/Plantilla-DIsparo-Secundario)_)
- mochadoom/gamelogic/Actions.java
- mochadoom/gamelogic/ActionsFunctions.java

**Comment by pablogomezm** [comment]
**Impact Analysis:** Módulos que deben son afectados por los cambios y deben ser adaptados
- mochadoom/gamelogic/Actions.java
- mochadoom/gamelogic/ActionsFunctions.java
- mochadoom/defines/StateNum.java
- mochadoom/doom/items.java
- mochadoom/doom/think_t.java
- mochadoom/data/info.java

**Comment by pablogomezm** [comment]
**Prefactoring:** La estrategia a ejecutar será modificar los módulos mencionados para agregar nuevas clases y métodos que definan un disparo secundario para la plasma gun, el procedimiento a seguir es similar a lo especificado en la wiki:
https://github.com/njara/mochadoom/wiki/Plantilla-DIsparo-Secundario

**Comment by pablogomezm** [comment]
Se implementaron los cambios, para probar se debe utilizar un iwad distinto del standard como iwad2. BUG: Al empezar una etapa activé el cheatcode idkfa para tener las armas, seleccione la plasma gun (arma 6) y al intentar disparar con click derecho el arma desaparece y el jugador no puede utilizar ninguna arma a menos que resetee el nivel.

**Comment by pablogomezm** [comment]
**Change propagation:** Se aplicó la estrategia señalada en prefactoring.
Commit asociado: https://github.com/njara/mochadoom/commit/ae50448c60a64d50372c78b9755954b63c4e64bf

**Comment by pablogomezm** [comment]
**Verification:** Luego de testear verifiqué que el disparo secundario se la Plasma gun tuviese un comportamiento distinto al disparo normal (por el ritmo de disparo y prints de test que dicen PlasmaAlternate).

**Comment by pablogomezm** [comment]
**Postfactoring:** Los cambios sirvieron para tener un disparo secundario pero se necesitarán cambios adicionales para un efecto en específico.

**Comment by pablogomezm** [comment]
**Conclusion:** Ya está implementada la capacidad de disparo secundario de la Plasma gun pero falta que éste aplique un efecto de quemado en los enemigos, lo cual corresponde al issue R19: https://github.com/njara/mochadoom/issues/28
