### ISSUE TITLE
RS29 - Modo alternativo: Rocket Launcher 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#30]
- Descripción: Modificar modo normal, para que considere cantidad de disparos preparados
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU22 - Modo alternativo Rocket launcher](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru22---modo-alternativo-rocket-launcher)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
## Concept Location

-ActionFunctions.java
-StateNum.java

Se busco donde realizar los cambios según la plantilla de disparo secundario.

**Comment by njara** [comment]
## Impact Analysis

Los archivos que se verían impactados según JRripples:
-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

**Comment by njara** [comment]
## Change Propagation.

-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

Se modificaron los archivos agregando los state del nuevo disparo y creando un metodo de disparo alternativo.

**Comment by njara** [comment]
## Conclusión

Se generó generó el metodo que considera la acumulación de balas para el disparo secundario.
