### ISSUE TITLE
RS30 - Modo alternativo: Rocket Launcher 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#31]
- Descripción: Efecto de preparar disparo adicional
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU22 - Modo alternativo Rocket launcher](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru22---modo-alternativo-rocket-launcher)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
## Concept Location

Los archivos a buscar los siguientes:
-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

Se buscará donde crear el método secundario.

**Comment by njara** [comment]
## Impact Analysis

Según JRipples
-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

**Comment by njara** [comment]
## Prefactoring

Según la plantilla de disparo secundario se aislaron los módulos a modificar.

**Comment by njara** [comment]
## Conclusión

Se generó el método de disparo secundario según la plantilla para disparo secundario. El arma acumula y genera los sprites según lo pedido.
