### ISSUE TITLE
RS31 - Modo alternativo: Machine Gun 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#32]
- Descripción: Efecto de sobrecalentamiento que dañe al jugador periódicamente. Se activa al disparar continuamente y se acaba luego de no disparar por un tiempo.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU21 - Modo alternativo Machine gun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru21---modo-alternativo-machine-gun)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [ ] Postfactoring
- [ ] Conclusion

**Comment by xZeok** [comment]
Inicialization: Añadir daño periodico al jugador al usar la MachineGun por sobrecalentamiento

**Comment by xZeok** [comment]
Concept Location:

/gamelogic/ActionFunctions.java
/doom/player_t.java

**Comment by xZeok** [comment]
Impact Analysis:

/gamelogic/ActionFunctions.java
/doom/player_t.java

**Comment by xZeok** [comment]
Prefactoring: Se modificara la clase player_t.java para hacer una funcion para que el jugador se dañe y se modificara ActionFunctions.java para que en el disparo alternativo de la MachineGun dañe al jugador.

**Comment by xZeok** [comment]
(falta que el daño se haga después de disparar durante un tiempo y luego se acabe luego de no disparar, temporalmente se daña al disparar)

**Comment by xZeok** [comment]
Change Propagation:

/gamelogic/ActionFunctions.java
/doom/player_t.java

**Comment by xZeok** [comment]
Verification:

Se comprobo que la funcionalidad requerida esta añadida, se reparo un bug en el daño por veneno para que realmente dañe al jugador. Ahora se daña al jugador al usar la machinegun por sobrecalentamiento y este daño es por el tiempo (se decidio hacer 30% de daño por el tiempo)

**Comment by xZeok** [comment]
Postfactoring: 

No se requiere

**Comment by xZeok** [comment]
Conclusion:

El disparo alternativo de la MachineGun daña al jugador por el tiempo
