### ISSUE TITLE
RS32 - Modo alternativo: Machine Gun 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#33]
- Descripción: Tipo de disparo con menor cooldown
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU21 - Modo alternativo Machine gun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru21---modo-alternativo-machine-gun)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by xZeok** [comment]
Inicialization: Añadir dispario secundario en MachineGun que tiene menor cooldown (dispara mas rapido)

**Comment by xZeok** [comment]
Concept Location: 

/gamelogic/ActionFunctions.java

**Comment by xZeok** [comment]
Impact Analisis:

/gamelogic/ActionFunctions.java
/data/info.java
/doom/think_k.java
/doom/items.java
/defines/StateNum.java

**Comment by xZeok** [comment]
Prefactoring: Se modificaran las funciones previamente señaladas agregando lo necesario para añadir el nuevo tipo de disparo, tambien se disminuirá la duracion del disparo disminuyendo los frames del disparo normal, con esto se logra disparar mas rápido.

**Comment by xZeok** [comment]
Change Propagation:

/gamelogic/ActionFunctions.java
/data/info.java
/doom/think_k.java
/doom/items.java
/defines/StateNum.java

**Comment by xZeok** [comment]
Verification:

Se comprobo que la funcionalidad requerida esta añadida, pero se encontro un bug al usar el cheatcode "idfa" que genera algunas armas que no estan implementadas, entonces al gastar todas las balas de cualquier arma, previamente habiendo hecho este cheatcode, se cambia automaticamente a una de estas armas provocando el error en el juego.

**Comment by xZeok** [comment]
Postfactoring: no se requiere

**Comment by xZeok** [comment]
Conclusion: Se añadio el nuevo modo de disparo en el cual hay menor cooldown. c3da2ac45ed4d453d85d85ac336f553215ec59c8
