### ISSUE TITLE
RS33 - Modo alternativo: Shotgun 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#34]
- Descripción: Efecto de daño en área y con recoil.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU20 - Modo alternativo Shotgun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru20---modo-alternarivo-shotgun)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [ ] Conclusion

**Comment by njara** [comment]
Initialization:
Se reutilizó el codigo generado por la issue RS34 - Modo alternativo: Shotgun 2

**Comment by njara** [comment]
Concept Location:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java

**Comment by njara** [comment]
Impact Analysis.

Solo se modificarán las clases:
/gamelogic/ActionFunctions.java
/gamelogic/Actions.java

**Comment by njara** [comment]
Prefactoring:

Se respaldo el codigo ya generado por la issue 34, y se aislo el metodo a modificar.

**Comment by njara** [comment]
Change Propagation, Verification.

Solo se añadieron código y la verificación se realizó por medio de un beta del juego.
Queda pendiente el recoil

**Comment by njara** [comment]
Postfactoring.
Se agregará el recoil del jugador al disparar el arma.

**Comment by njara** [comment]
Actualmente se está buscando donde generar el recoil, debido a que no es posible modificar la clase jugador sin que afecte los desarrollos en paralelo. Por lo que se generará una reunión con el grupo jugador para finalizar esta issue.

**Comment by njara** [comment]
Se generó el recoil para la shotgun.
