### ISSUE TITLE
RS34 - Modo alternativo: Shotgun 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#35]
- Descripción: Tipo de disparo que usa más balas y hace más daño.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU20 - Modo alternativo Shotgun](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru20---modo-alternarivo-shotgun)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
Concept Location:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java

**Comment by njara** [comment]
Impact Analysis:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java
/data/info.java
/doom/think_k.java
/defines/StateNum.java

**Comment by njara** [comment]
Prefactoring, Change Propagation, Postfactoring y Verification:

No fueron requeridos prefactoring ni postfactoring. La verificación fue realizada y los cambios fueron principalmente adiciones evidentes (explicación general en issue disparo alternativo).

**Comment by njara** [comment]
Conclusion:

Se ha creado el modo secundario para la escopeta, que consume 2 balas y realiza mas daño.
