### ISSUE TITLE
RS35 - Modo alternativo: Pistol 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#36]
- Descripción: Crear clase de efecto de bengala, con posición, duración y efecto de atracción a los zombies (gasta 10 balas y tiene un area de efecto limitada).
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU19 - Modo alternativo Pistol](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru19---modo-alternativo-pistol)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
Concept Location:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java

**Comment by njara** [comment]
Impact Analysis

/data/info.java
/data/mobjinfo/Flare_t.java
/data/mobjtype_t.java
/gamelogic/ActionFunctions.java
/gamelogic/Actions.java
/gamelogic/UnifiedGameMap.java
/rendering/VisSprites.java

**Comment by njara** [comment]
Prefactoring, Change Propagation, Postfactoring y Verification:

No fueron requeridos prefactoring ni postfactoring. Se reviso mediante debug, que la bengala no dañara a los zombies y que esta fuera afectada por la gravedad.

**Comment by njara** [comment]
Tras el correcto funcionamiento, se pusheo y se le dio a conocer al grupo Zombie para que trabajen en la issue RS43, que consiste en que los zombies sean atraídos a la bengala.
