### ISSUE TITLE
RS36 - Modo alternativo: Pistol 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#37]
- Descripción: Agregar efecto de disparo secundario para la pistola.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU19 - Modo alternativo Pistol](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru19---modo-alternativo-pistol)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by masotrix** [comment]
Concept Location:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java

**Comment by masotrix** [comment]
Impact Analysis:

/gamelogic/ActionFunctions.java
/gamelogic/Actions.java
/data/info.java
/doom/thinkk.java
/defines/StateNum.java

**Comment by masotrix** [comment]
Prefactoring, Change Propagation, Postfactoring y Verification:

No fueron requeridos prefactoring ni postfactoring. La verificación fue realizada y los cambios fueron principalmente adiciones evidentes (explicación general en issue disparo alternativo).

**Comment by masotrix** [comment]
Conclusion:

Se ha dejado preparado el concepto de disparo alternativo para la pistola. Su desarrollo posterior será realizado en su issue 2 correspondiente.

**Comment by njara** [comment]
Se cerraron los item de la issue
