### ISSUE TITLE
RS37 - Modo alternativo: Fist y Chainsaw 1

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#38]
- Descripción: Aumentar daño, y aumentar cooldown de disparo.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU18 - Modo alternativo Fist/chainsaw](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru18---modo-alternativo-fistchainsaw)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
## Concept Location

Se buscó donde generar los cambios.
-ActionFunctions.java
-items.java

**Comment by njara** [comment]
## Impact Analysis

Según JRipples
-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

**Comment by njara** [comment]
## Change Propagation

Se reutilizó el código del disparo y golpe normal, y se realizaron modificaciones en el daño y en el cooldown para cumplir dicha issue.

**Comment by njara** [comment]
Se generó y probó lo solicitado.
