### ISSUE TITLE
RS38 - Modo alternativo: Fist y Chainsaw 2

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#39]
- Descripción: Cambiar posición de animación de golpe a la cabeza.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU18 - Modo alternativo Fist/chainsaw](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru18---modo-alternativo-fistchainsaw)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
## Concept Location

Se busco donde modificar para generar el disparo secundario del golpe.
-ActionFunctions.java
-StateNum.java

**Comment by njara** [comment]
## Impact Analysis

Según JRipples
-ActionFunctions.java
-DoomMain.java
-StateNum.java
-info.java
-items.java
-think_t.java

**Comment by njara** [comment]
## Verification

Se agregó el golpe secundario en los archivos items.java y ActionFunctions.java.

**Comment by njara** [comment]
Se generó la instancia del disparo secundario.
