### ISSUE TITLE
RS39 - Disparo alternativo de armas

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#40]
- Descripción: Crear atributo de disparo alternativo a las armas
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU17 - Modo alternativo Uso alternativo de armas](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru17---uso-alternativo-en-armas)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by njara** [comment]
#### Initialization

Se comenzó a buscar la ubicación de los modos de disparos primarios, para luego crear el secundario.
Se detecto en el codigo, que el click Secundario es el numero 3.

**Comment by masotrix** [comment]
Concept Location:

Las clases directamente asociadas a disparar son
/gamelogic/ActionFunctions.java
/gamelogic/UnifiedGameMap.java
/doom/DoomMain.java

**Comment by masotrix** [comment]
Impact Analysis:

Las clases en total afectadas son:
/gamelogic/ActionFunctions.java
/gamelogic/UnifiedGameMap.java
/gamelogic/Actions.java
/doom/DoomMain.java
/doom/weaponinfo_t.java
/doom/items.java
/doom/think.java
/defines/StateNum.java
/data/info.java
/data/Defines.java
/finale/EndLevel.java

**Comment by masotrix** [comment]
Prefactoring y Change Propagation:

  La cantidad de cambios necesarios es tal que se decidió realizar la menor cantidad de cambios adicionales posibles. Los cambios finalmente realizados involucran principalmente la adicion de funcionalidad, pues existía el "espacio" para la adición sin cambios que no estuvieran relación alguna con la acción de disparar, a pesar de que se considera que existe una gran cantidad de code duplication.

**Comment by masotrix** [comment]
Verification, Postfactoring y Conclusión:

Ya ha sido probado en una máquina, y pareciera no requerirse un postfactoring notorio.
Finalmente, la issue ha concluido con dejar el código preparado para implementar sobre él
disparos alternativos para cada arma.
