### ISSUE TITLE
RS40 - Boton para disparar de forma alternativa

### ISSUE THREAD

**Issue by elbraulio** [njara/mochadoom#41]
- Descripción: Implementar un botón para disparar de forma alternativa.
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisito de Usuario asociado
[RU17 - Modo alternativo Uso alternativo de armas](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru17---uso-alternativo-en-armas)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by masotrix** [comment]
Concept Location:

Lugar donde se verifica (mientras se está jugando) si se apretó el click izquierdo para disparar: 
-DoomMain -> BuildTiccmd

En este lugar se puede verificar si se apretó el click derecho, pues la misma función empleada (mousebuttons) con un distinto argumento (mousebstrafe = 2) entregaría si tal acción fue realizada.

**Comment by masotrix** [comment]
Impact analysis, prefactoring, change propagation, verification y postfactoring:

-La clase que necesita cambios es únicamente DoomMain, pues se requiere únicamente la adición de una condición en un if.

-De la misma forma, no es necesario un prefactoring, no se realiza una propagación posterior ni un post factoring.

-La verificación es fácilmente realizada al correr el juego y probar disparar al realizar un click derecho.

**Comment by masotrix** [comment]
Conclusion:

Se averiguó satisfactoriamente el lugar indicado para lograr realizar disparos alternativos mediante el click derecho.
