### ISSUE TITLE
RS43 - Sistema Atracción Zombie-Jugador

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#44]
- Descripción: Los Zombies son atraidos por los jugadores cuando estos se encuentran en su campo visual.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU09 - Atraccion Zombie-Jugador y Zombie-Monstruo](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru09---atraccion-zombie-jugador-y-zombie-monstruo)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by elbraulio** [comment]
Initialization:
Jugador atrae a los zombies

**Comment by elbraulio** [comment]
Concept Location:
Ninguna Clase.

**Comment by elbraulio** [comment]
Impact Analysis:
Ninguna clase.

**Comment by elbraulio** [comment]
Prefactoring:
No se hacen cambios

**Comment by elbraulio** [comment]
Change propagation:
No hay cambios.

**Comment by elbraulio** [comment]
Verification:
No hay cambios.

**Comment by elbraulio** [comment]
Postfactoring:
No hay cambios

**Comment by elbraulio** [comment]
Conlusion:
Ya estaba implementado en el juego, por lo que no se necesito modificar ninguna clase.
