### ISSUE TITLE
RS44 - Sistema atracción Zombie-Monstruo

### ISSUE THREAD

**Issue by juakotorres** [njara/mochadoom#45]
- Descripción: Los Zombies son atraidos por los monstruos cuando estos se encuentran en su campo visual.  
- Fuente: Analista.  
- Prioridad: Crítica.  
- Estabilidad: Intransable.  
- Fecha Actualización: 4/12/2016 12:12  
- Estado: No Cumple.  
- Incremento: 0  
- Tipo: Funcional.  
- Usuario Asociado: Usuario de la aplicación.  

Requisitos de Usuario asociados
[RU09 - Atraccion Zombie-Jugador y Zombie-Monstruo](https://github.com/njara/mochadoom/wiki/Requisitos-de-Usuario#ru09---atraccion-zombie-jugador-y-zombie-monstruo)
- [x] Initialization  
- [x] Concept Location  
- [x] Impact Analysis  
- [x] Prefactoring  
- [x] Change Propagation  
- [x] Verification  
- [x] Postfactoring  
- [x] Conclusion

**Comment by njara** [comment]
**Initialization**

Los zombies son atraidos por los monstruos.

**Comment by njara** [comment]
**Concept Location**

zombie, monster, thinker.

**Comment by njara** [comment]
**Impact Analysis**

Análisis con JRipples.
Clases que se podrían ver impactadas:
- ActionsFunctions
- UnifiedGameMap
- DoomStatusAware
- RendererState
- Actions
- ThinkerList
- player_t
- VanillaDSG
- mobj_t
- AbstractLevelLoader
- DoomMain
- DoomContext
- SlideDoor
- Wiper
- AWTDoom
- EndLevel
- Map
- MochaEvents
- ParallelRenderer
- Main
- DoomFrame
- TestSuperSound
- DoomSystem
- LevelLoaderTester
- AbstractStatusBar
- TestClassicSound
- TestClipSound
- DummyNetworkDriver
- HU
- IVideoScaleAware
- IDoomGameNetworking
- IDoomGame
- IDoom

**Comment by njara** [comment]
**Prefactoring**

Se implemento en primera instancia el cambio y los zombies eran atraidos por los monstruos, pero esto afectaba la jugabilidad de juego ya que los zombies al ser atraídos por los monstruos peleaban con ellos y se eliminaban antes de encontrarse con el jugador, por lo que se decidió que no se harán cambios.

**Comment by njara** [comment]
**Change Propagation**

No se cambió codigo.

**Comment by njara** [comment]
**Verification**

No hubo cambios.

**Comment by njara** [comment]
**Postfactoring**

No es necesario, ya que no hubo cambios.

**Comment by njara** [comment]
**Conclusion**

Los zombies no serán atraidos por monstruos.
