### ISSUE TITLE
Rotación rara de cámara

### ISSUE THREAD

**Issue by pablogomezm** [njara/mochadoom#54]
Al iniciar el juego y mover la cámara, ésta se mueve de manera errática hacia todos lados por unos segundos, luego se arregla solo.
Ocurre con varios iwad y tanto con mousepad como con mouse.

**Comment by masotrix** [comment]
Al parecer se debe a que el mouse no ha sido correctamente identificado por el programa. De hecho, puede moverse el mouse fuera de la ventana y al volver a ingresarlo, el bug deja de ocurrir.
